server:
  port: 8070

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  datasource:
    username: root
    password: 123456
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB