server:
  port: 9200
spring:
  profiles:
    active: dev
  application:
    name: ananops-provider-imc
  datasource:
    username: root
    password: 123456
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB